### ISSUE TITLE
Toolbar Flashes before showing the keyboard

### ISSUE THREAD

**Issue by camdagr8** [don/KeyboardToolbarRemover#13]
I noticed that on iOS 7.1.1 cordova 3.1.0 that the keyboard toolbar flashes for a quick second when the keyboard is shown. It goes away, but it looks like a glitch to the end user.

**Comment by camdagr8** [comment]
The screen also jumps down then back up.

**Comment by don** [comment]
I recommend using the Cordova [Keyboard Plugin](https://github.com/apache/cordova-plugins/tree/master/keyboard)  instead of this one. The Cordova Keyboard Plugin has better support for resizing and works with Cordova 3.2+. Where possible I keep my projects on the latest Cordova, so I'm not putting more effort into this plugin.
